### PR TITLE
all: Initial support for dynamic attributes

### LINKED ISSUE #94: Support Dynamic Types
## Description

terraform-plugin-framework now supports dynamic types and attributes. The code generation specification and Go bindings can be enhanced now with that support.

## References

- https://github.com/hashicorp/terraform-plugin-codegen-openapi/issues/82

### PR DESCRIPTION
**Pull request by bflad**
Closes #94

Adds initial support for dynamic attributes in data source, provider, and resource schemas.

### CODE REVIEW

**Review by austinvalle — APPROVED** [review]
Changes look great! One general question

Are we intentionally leaving `dynamic` out of the [object attribute types](https://github.com/hashicorp/terraform-plugin-codegen-spec/blob/2a8230bcc5588ca27dfdcf47ec0ab7f2e02a927f/spec/v0.1/schema.json#L545-L579) to avoid the `list -> object -> dynamic` problem? If so, should we also add a comment to the object attribute type to mention this?

**Comment by bflad** [comment]
> Are we intentionally leaving dynamic out of the [object attribute types](https://github.com/hashicorp/terraform-plugin-codegen-spec/blob/2a8230bcc5588ca27dfdcf47ec0ab7f2e02a927f/spec/v0.1/schema.json#L545-L579)

Nope, that is a miss on my part. Will add. Good catch.

**Comment by bflad** [comment]
Added in https://github.com/hashicorp/terraform-plugin-codegen-spec/pull/98/commits/d2ffa9c611e551d88ff99d26d49898d3440555cb if you could please take a look

**Review by austinvalle — APPROVED** [review]
🚀 - LGTM

**Pull request merged**
